# Generated by Django 3.2.4 on 2023-08-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.IntegerField(max_length=16, null=True),
        ),
    ]
