version: "3.8"
services:
    websocket:
        build:
            dockerfile: ./flask_microservice/Dockerfile
        ports:
            - "8001:8001"
    
    api:
        build:
            dockerfile: ./django_microservice/Dockerfile
        ports:
            - "8000:8000"
        command: python manage.py runserver 0.0.0.0:8000
    




